apiVersion: v1
kind: Service
metadata:
  name: gamestart-backend
  namespace: default
spec:
  selector:
    app: gamestart
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000